@echo OFF
REM set HOMEDRIVE=%USERPROFILE%
set ANYPOINT_HOME=##ASDIR##
set PACKAGE_HOME=%~dp0
set M2_HOME=%PACKAGE_HOME%\maven
set MAVEN_HOME=%PACKAGE_HOME%\maven
set ANYPOINT_JVM=##JDKDIR##
set JAVA_HOME=%ANYPOINT_JVM%
set PATH=%JAVA_HOME%\bin;%M2_HOME%\bin;%PATH%
set M2_REPO=%PACKAGE_HOME%\artifacts
